name: life_change_pj_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.2

  # firebase_core: ^0.4.0+9
  # firebase_core: ^0.4.5
  # cloud_firestore: ^0.12.9+5
  # cloud_firestore: ^0.13.6
  # firebase_analytics: ^5.0.2
  # firebase_auth: ^0.14.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # module:
    # androidX: true # Add this line.
